### PR TITLE
tags used instead of skip-tags for skip example

### PR DESCRIPTION
**Pull request by arbabnazar**
@lenards @johnworth @ianmcorvidae @dennisroberts71 @jerry57 kindly review the change. Thanks

### CODE REVIEW

**Comment by lenards** [comment]
I'd give this a 👍 

The suggested context is _only_ plays/roles not matching `'sudoers'` (aka "skip any `'sudoers'` tags plays/roles"). 

```
$ ansible --version 
ansible 2.1.0.0
  config file = /opt/dev/atmosphere-ansible/ansible/ansible.cfg
  configured module search path = ['/usr/share/ansible']
$ ansible-playbook --help | grep -A3 tags
  --list-tags           list all available tags
  --list-tasks          list all tasks that would be executed
  -M MODULE_PATH, --module-path=MODULE_PATH
                        specify path(s) to module library
--
  --skip-tags=SKIP_TAGS
                        only run plays and tasks whose tags do not match these
                        values
  --start-at-task=START_AT_TASK
                        start the playbook at the task matching this name
--
  -t TAGS, --tags=TAGS  only run plays and tasks tagged with these values
  --vault-password-file=VAULT_PASSWORD_FILE
                        vault password file
  -v, --verbose         verbose mode (-vvv for more, -vvvv to enable
```

**Comment by lenards** [comment]
@nfaction / @amercer1

**Comment by nfaction** [comment]
Great catch @arbabnazar ! Thank you for your pull request!!

**Comment by arbabnazar** [comment]
Thanks @nfaction

**Pull request merged**
